#Linear regression using pytorch built-in 

let's begain with importing the torch.nn package from pytorch , which contains the utility classes for building neural network

In [27]:
import torch.nn as nn

In [28]:
import torch

as before we represented the inputs and targets and matrixs 

In [29]:
import numpy as np


In [30]:
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70], 
                   [74, 66, 43], 
                   [91, 87, 65], 
                   [88, 134, 59], 
                   [101, 44, 37], 
                   [68, 96, 71], 
                   [73, 66, 44], 
                   [92, 87, 64], 
                   [87, 135, 57], 
                   [103, 43, 36], 
                   [68, 97, 70]], 
                  dtype='float32')

# Targets (apples, oranges)
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119],
                    [57, 69], 
                    [80, 102], 
                    [118, 132], 
                    [21, 38], 
                    [104, 118], 
                    [57, 69], 
                    [82, 100], 
                    [118, 134], 
                    [20, 38], 
                    [102, 120]], 
                   dtype='float32')

inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [31]:
inputs

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.],
        [ 74.,  66.,  43.],
        [ 91.,  87.,  65.],
        [ 88., 134.,  59.],
        [101.,  44.,  37.],
        [ 68.,  96.,  71.],
        [ 73.,  66.,  44.],
        [ 92.,  87.,  64.],
        [ 87., 135.,  57.],
        [103.,  43.,  36.],
        [ 68.,  97.,  70.]])

We are using 15 training examples to illustrate how to work with large datasets in small batches. 

#Dataset and DataLoader 
we'll create a tensor dataset , which allows access to rows of inputs and target as tuples and provides standard API's for working with many different types of datasets 

In [32]:
from torch.utils.data import TensorDataset

In [33]:
#define dataset 
train_ds=TensorDataset(inputs,targets)
train_ds[:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]), tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

the TensorDataset allows us to access small section of the  training data using the array indexing notation ([:3] in the above code). it returns the tuples with two elements . the 1st element contains the input variables for the selected row and the second contains the target 

we'll also create a dataLoader , which can split the data into batches of a predefined size while training . It also provides other utilites like surffing and random sampling of the data 

In [34]:
from torch.utils.data import DataLoader

In [35]:
#define dataLoader 
batch_size=5
train_dl=DataLoader(train_ds,batch_size,shuffle=True )

we can use the dataLoader in a for loop 

In [36]:
inputs

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.],
        [ 74.,  66.,  43.],
        [ 91.,  87.,  65.],
        [ 88., 134.,  59.],
        [101.,  44.,  37.],
        [ 68.,  96.,  71.],
        [ 73.,  66.,  44.],
        [ 92.,  87.,  64.],
        [ 87., 135.,  57.],
        [103.,  43.,  36.],
        [ 68.,  97.,  70.]])

In [37]:
for xb,yb in train_dl:
  print(xb)
  print(yb)
  break

tensor([[ 92.,  87.,  64.],
        [103.,  43.,  36.],
        [102.,  43.,  37.],
        [101.,  44.,  37.],
        [ 68.,  96.,  71.]])
tensor([[ 82., 100.],
        [ 20.,  38.],
        [ 22.,  37.],
        [ 21.,  38.],
        [104., 118.]])


by comparing the inputs with the batches (xb,yb)create above we can see that the data is shuffle (shuffle=True)

in each itrration the dataloader returns one batch of data with the given batch size .If shuffle is set to True ,it shuffle the data before creating batches .Shuffling helps randamize the input to the optimization algorithum .Leading to the fast reduction in the loss 

the more there is randamization , the faster the model trains 

##nn.Linear 
instead of initializing the weights & baises manually , we can define the model using nn.Linear class from pyTorch , which does it automatically 

In [38]:
#define model 
model=nn.Linear(3,2)#3=inputs(temp,rainfall,humidity)2=output(yeild of apples ,yeild of oranges )
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[-0.0312, -0.3717,  0.0782],
        [-0.1819, -0.0766, -0.3343]], requires_grad=True)
Parameter containing:
tensor([-0.2450, -0.1368], requires_grad=True)


pytorch model also have a helpfull .paremeters method , which returns a list containing all the weights and baises matrix present in the model .for our linear regression model , we have one weight matrix and one baises matrix  

In [39]:
#parameters
list(model.parameters())

[Parameter containing:
 tensor([[-0.0312, -0.3717,  0.0782],
         [-0.1819, -0.0766, -0.3343]], requires_grad=True),
 Parameter containing:
 tensor([-0.2450, -0.1368], requires_grad=True)]

we can use the model to genarate pridiction in same way as before 

In [40]:
#genarate pridiction 
preds=model(inputs )
preds

tensor([[-24.0676, -32.9186],
        [-30.7939, -44.8204],
        [-48.2377, -45.6088],
        [-16.5207, -34.3503],
        [-32.6117, -43.4370],
        [-23.7271, -33.0239],
        [-30.3440, -45.0781],
        [-48.1907, -46.1250],
        [-16.8612, -34.2449],
        [-32.5023, -43.5894],
        [-23.6177, -33.1763],
        [-30.4534, -44.9257],
        [-48.6876, -45.3511],
        [-16.6302, -34.1978],
        [-32.9522, -43.3317]], grad_fn=<AddmmBackward>)

##Loss Function 
instead of defining loss function  manually we can use the built-in loss function "mse_loss"

In [41]:
# importing nn function 
import torch.nn.functional as F

the nn.functional  package contains many usefull loss function and several other utilities   

In [42]:
#define loss function 
loss_fn=F.mse_loss

let's compute the loss for the current prediction of our  model 

In [43]:
loss=loss_fn(model(inputs),targets)
print(loss)

tensor(16181.5654, grad_fn=<MseLossBackward>)


##optimizer
instead of manuallly manupalating the models's weights and baises using gradiants, we can use the optimizer optim.SGD (stochastic gradiant decent ).Stochastic indicates that samples are selected in random batches instead of a single group 

In [44]:
#defining optimizer
opt=torch.optim.SGD(model.parameters(),lr=1e-5)

Note that the model.parameters() is passed as an argument to optim.SGD so that the optimizer knows which matrix to be modified during the update step .also we can specify a learning rate that contraols the amount by which the parameters are modified  

## Train the model
we are now ready to train the model . We'll follow the same steps to implement gradiant decent 

*   genarate prediction
*   calculate the loss 
*   compute gradient w.r.t weights and baises 
*   adjust the weights by substracting a small quantity proportional to gradient 
*   rest the gradient to zero 

the only change is that we'll work on batches of data instead of processing the entire  training data  in every itration . Let's define a utility function fit that train the model for a given number of epochs 






In [45]:
#utility function to train the model 
def fit (num_epochs, model,loss_fn,opt, train_dl):

  #repeat for the given number of epochs 
  for epoch in range (num_epochs):

    #train the batchs of data 
    for xb, yb in train_dl:

      #1 genarate pridiction 
      pred=model(xb)

      #2 calculate the loss 
      loss=loss_fn(pred,yb)

      #3 compute gradiant 
      loss.backward()

      #4 update parameters using gradiant 
      opt.step()

      #5 reset the gradiant to zero
      opt.zero_grad()

      #6 print the progress
      if(epoch+1)  % 10==0:
        print("Epoch [{},{}] , Loss :{:.4f", format(epoch+1), num_epochs,loss.item())




### somethings to note above
*   we use the data loader defined earlier to get batches of data for every itration.
*   instead of updating parameters(weights & baises) manualy we use opt.step to perform the update and opt.zero_grad to reset the gradiant to zero
*    we also add the log statment that prints the loss from the last batch of data for every 10th epoch to track the traning progress . loss.item retures the actual value stored in the loss tensor 

Let's train the model for 100 epochs



In [46]:
fit(100,model,loss_fn,opt,train_dl)

Epoch [{},{}] , Loss :{:.4f 10 100 575.7686157226562
Epoch [{},{}] , Loss :{:.4f 10 100 561.189453125
Epoch [{},{}] , Loss :{:.4f 10 100 227.7239990234375
Epoch [{},{}] , Loss :{:.4f 20 100 191.1906280517578
Epoch [{},{}] , Loss :{:.4f 20 100 481.578857421875
Epoch [{},{}] , Loss :{:.4f 20 100 265.64825439453125
Epoch [{},{}] , Loss :{:.4f 30 100 85.33868408203125
Epoch [{},{}] , Loss :{:.4f 30 100 196.93658447265625
Epoch [{},{}] , Loss :{:.4f 30 100 366.71490478515625
Epoch [{},{}] , Loss :{:.4f 40 100 158.9788360595703
Epoch [{},{}] , Loss :{:.4f 40 100 152.7715606689453
Epoch [{},{}] , Loss :{:.4f 40 100 147.2421875
Epoch [{},{}] , Loss :{:.4f 50 100 111.38907623291016
Epoch [{},{}] , Loss :{:.4f 50 100 46.761436462402344
Epoch [{},{}] , Loss :{:.4f 50 100 179.88851928710938
Epoch [{},{}] , Loss :{:.4f 60 100 80.71263122558594
Epoch [{},{}] , Loss :{:.4f 60 100 107.94194030761719
Epoch [{},{}] , Loss :{:.4f 60 100 62.642967224121094
Epoch [{},{}] , Loss :{:.4f 70 100 52.06037521362

In [47]:
preds=model(inputs)
preds

tensor([[ 58.3841,  71.9045],
        [ 82.1250,  97.3528],
        [116.2817, 139.0346],
        [ 28.8183,  45.1036],
        [ 97.2610, 108.5412],
        [ 57.3420,  70.8867],
        [ 81.8837,  96.7427],
        [116.5839, 139.2927],
        [ 29.8604,  46.1215],
        [ 98.0618, 108.9490],
        [ 58.1428,  71.2944],
        [ 81.0829,  96.3349],
        [116.5231, 139.6447],
        [ 28.0176,  44.6958],
        [ 98.3031, 109.5591]], grad_fn=<AddmmBackward>)

In [48]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 57.,  69.],
        [ 80., 102.],
        [118., 132.],
        [ 21.,  38.],
        [104., 118.],
        [ 57.,  69.],
        [ 82., 100.],
        [118., 134.],
        [ 20.,  38.],
        [102., 120.]])

indeed ,the prediction are close to the target. we have a trained a resonably good model to pridict crop yeild for apples and oranges by looking at the avgrage temperature , rainfall,and humidity in a reign. we can use this to make pridiction of crop yeild for new regions by passinf a batch of single row of inputs 

In [49]:
model(torch.tensor([[75,63,44.]]))

tensor([[55.2658, 68.3156]], grad_fn=<AddmmBackward>)

the pridicted yeild of apple is 54.33 tons per hector and that of oranges is 69.30 tons per hector 

## Machine Learning vs. Classical Programming

 we've defined a "model" that assumes a specific relationship between the inputs and the outputs, expressed using some unknown parameters (weights & biases). We then show the model some know inputs and outputs and _train_ the model to come up with good values for the unknown parameters. Once trained, the model can be used to compute the outputs for new inputs.

This paradigm of programming is known as _machine learning_, where we use data to figure out the relationship between inputs and outputs. _Deep learning_ is a branch of machine learning that uses matrix operations, non-linear activation functions and gradient descent to build and train models. Andrej Karpathy, the director of AI at Tesla Motors, has written a great blog post on this topics, titled [Software 2.0](https://medium.com/@karpathy/software-2-0-a64152b37c35).

This picture from book [Deep Learning with Python](https://www.manning.com/books/deep-learning-with-python) by Francois Chollet captures the difference between classical programming and machine learning:

![](https://i.imgur.com/oJEQe7k.png)

lets make model 2 


In [52]:
#convert machine learning model to deep learning model
model2=nn.Sequential(nn.Linear(3,3),nn.Sigmoid(),nn.Linear(3,2))

In [54]:
opt=torch.optim.SGD(model2.parameters(),lr=1e-4)

In [55]:
fit(100,model2,F.mse_loss,opt,train_dl)

Epoch [{},{}] , Loss :{:.4f 10 100 8228.0078125
Epoch [{},{}] , Loss :{:.4f 10 100 10363.41015625
Epoch [{},{}] , Loss :{:.4f 10 100 6055.392578125
Epoch [{},{}] , Loss :{:.4f 20 100 8151.2685546875
Epoch [{},{}] , Loss :{:.4f 20 100 10260.01171875
Epoch [{},{}] , Loss :{:.4f 20 100 5975.1845703125
Epoch [{},{}] , Loss :{:.4f 30 100 8718.138671875
Epoch [{},{}] , Loss :{:.4f 30 100 9707.4130859375
Epoch [{},{}] , Loss :{:.4f 30 100 5712.47021484375
Epoch [{},{}] , Loss :{:.4f 40 100 5072.94677734375
Epoch [{},{}] , Loss :{:.4f 40 100 10255.255859375
Epoch [{},{}] , Loss :{:.4f 40 100 8564.5224609375
Epoch [{},{}] , Loss :{:.4f 50 100 5647.001953125
Epoch [{},{}] , Loss :{:.4f 50 100 10107.3232421875
Epoch [{},{}] , Loss :{:.4f 50 100 7895.97265625
Epoch [{},{}] , Loss :{:.4f 60 100 5783.1943359375
Epoch [{},{}] , Loss :{:.4f 60 100 6864.0029296875
Epoch [{},{}] , Loss :{:.4f 60 100 10763.552734375
Epoch [{},{}] , Loss :{:.4f 70 100 8470.3857421875
Epoch [{},{}] , Loss :{:.4f 70 100 843

## Introduction to Machine Learning

<img src="https://i.imgur.com/oJEQe7k.png" width="480" />

<div style="text-align:center;">
    <a href="https://www.manning.com/books/deep-learning-with-python">Image Source</a>
</div>

### Linear Regression

#### Linear Regression Data

<img src="https://i.imgur.com/mtkR2lB.png" width="540" >

#### Linear Regression Visualization

<img src="https://i.imgur.com/mtkR2lB.png" width="480">


#### Linear Regression model

$$
\hspace{2.5cm} X \hspace{1.1cm} \times \hspace{1.2cm} W^T \hspace{1.2cm}  + \hspace{1cm} b \hspace{2cm}
$$

$$
\left[ \begin{array}{cc}
73 & 67 & 43 \\
91 & 88 & 64 \\
\vdots & \vdots & \vdots \\
69 & 96 & 70
\end{array} \right]
%
\times
%
\left[ \begin{array}{cc}
w_{11} & w_{21} \\
w_{12} & w_{22} \\
w_{13} & w_{23}
\end{array} \right]
%
+
%
\left[ \begin{array}{cc}
b_{1} & b_{2} \\
b_{1} & b_{2} \\
\vdots & \vdots \\
b_{1} & b_{2} \\
\end{array} \right]
$$

### Feedfoward Neural Network

![ffnn](https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/Multi-Layer_Neural_Network-Vector-Blank.svg/400px-Multi-Layer_Neural_Network-Vector-Blank.svg.png)

Conceptually, you think of feedforward neural networks as two or more linear regression models stacked on top of one another with a non-linear activation function applied between them.

<img src="https://cdn-images-1.medium.com/max/1600/1*XxxiA0jJvPrHEJHD4z893g.png" width="640">

To use a feedforward neural network instead of linear regression, we can extend the `nn.Module` class from PyTorch.